"""
PEVN Backend — Database Model Registry

Imports Base from base_class and re-exports all domain models so Alembic
can discover all metadata.
"""

from __future__ import annotations

from app.db.base_class import Base
from app.models import (
    AcademicAssignment,
    AcademicPeriod,
    AcademicYear,
    AuditLog,
    Campus,
    Department,
    DocumentType,
    EducationalLevel,
    Enrollment,
    Grade,
    Group,
    GroupTransferHistory,
    Guardian,
    GuardianInvitation,
    Institution,
    KnowledgeArea,
    MeetingAttendance,
    MeetingRecording,
    Municipality,
    PasswordResetToken,
    Permission,
    RectorInvitation,
    RefreshToken,
    Role,
    RolePermission,
    Student,
    StudentGuardian,
    Subject,
    Teacher,
    User,
    UserRole,
    VirtualClassroom,
)

__all__ = [
    "AcademicAssignment",
    "AcademicPeriod",
    "AcademicYear",
    "AuditLog",
    "Base",
    "Campus",
    "Department",
    "DocumentType",
    "EducationalLevel",
    "Enrollment",
    "Grade",
    "Group",
    "GroupTransferHistory",
    "Guardian",
    "GuardianInvitation",
    "Institution",
    "KnowledgeArea",
    "MeetingAttendance",
    "MeetingRecording",
    "Municipality",
    "PasswordResetToken",
    "Permission",
    "RectorInvitation",
    "RefreshToken",
    "Role",
    "RolePermission",
    "Student",
    "StudentGuardian",
    "Subject",
    "Teacher",
    "User",
    "UserRole",
    "VirtualClassroom",
]
