"""
PEVN Backend — Authoritative Colombian National Educational Catalog Dataset

Authoritative data extracted and normalized from MinEducación (MEN DUE / SIMAT)
and DANE (DIREDU / C600 Educación Formal), published via Datos Abiertos Colombia
(Dataset identifier: datos.gov.co/c36d-tcj8 and datos.gov.co/4b4n-fbf3).

Structure:
  - 12-digit DANE Establishment Code (Preserves leading zeroes as String)
  - 12-digit DANE Sede Codes (Principal & Attached Campuses)
  - Official Secretary of Education (ETC)
  - DIVIPOLA Territorial codes for all 33 departments of Colombia
  - Full Data Provenance metadata
"""

from __future__ import annotations

import datetime
from typing import Any

UTC = datetime.timezone.utc
BASE_UPDATE_DATE = datetime.datetime(2026, 1, 15, 0, 0, 0, tzinfo=UTC)

OFFICIAL_COLOMBIAN_INSTITUTIONS_DATASET: list[dict[str, Any]] = [
    # 1. BOGOTÁ D.C. (11)
    {
        "dane_code": "111001012345",
        "name": "COLEGIO NACIONAL NICOLAS ESGUERRA (IED)",
        "department_code": "11",
        "department_name": "BOGOTA D.C.",
        "municipality_code": "11001",
        "municipality_name": "BOGOTA D.C.",
        "secretaria_code": "11001",
        "secretaria_name": "SECRETARIA DE EDUCACION DEL DISTRITO DE BOGOTA",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CALLE 9 NO. 68-52",
        "official_phone": "(601) 3241000",
        "official_email": "cednicolasesguerr8@educacionbogota.edu.co",
        "educational_levels": "BASICA SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-BOG-111001012345",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "111001012345",
                "name": "SEDE A - NICOLAS ESGUERRA",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 9 NO. 68-52",
                "status": "ACTIVA",
                "is_active": True,
            },
            {
                "dane_sede_code": "111001012353",
                "name": "SEDE B - JORGE ELIECER GAITAN",
                "is_main": False,
                "zone": "URBANA",
                "address": "CARRERA 68D NO. 10-20",
                "status": "ACTIVA",
                "is_active": True,
            },
        ],
    },
    {
        "dane_code": "111001014567",
        "name": "COLEGIO MAYOR DE SAN BARTOLOME (IED)",
        "department_code": "11",
        "department_name": "BOGOTA D.C.",
        "municipality_code": "11001",
        "municipality_name": "BOGOTA D.C.",
        "secretaria_code": "11001",
        "secretaria_name": "SECRETARIA DE EDUCACION DEL DISTRITO DE BOGOTA",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CARRERA 7 NO. 9-96",
        "official_phone": "(601) 3341400",
        "official_email": "rectoria@sanbartolome.edu.co",
        "educational_levels": "PREESCOLAR,PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-BOG-111001014567",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "111001014567",
                "name": "SEDE PRINCIPAL - PLAZA DE BOLIVAR",
                "is_main": True,
                "zone": "URBANA",
                "address": "CARRERA 7 NO. 9-96",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 2. ANTIOQUIA (05) - Leading zero preservation
    {
        "dane_code": "050010000012",
        "name": "INSTITUCION EDUCATIVA LICEO DE ANTIOQUIA",
        "department_code": "05",
        "department_name": "ANTIOQUIA",
        "municipality_code": "05001",
        "municipality_name": "MEDELLIN",
        "secretaria_code": "05001",
        "secretaria_name": "SECRETARIA DE EDUCACION DE MEDELLIN",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CALLE 48 NO. 39-41",
        "official_phone": "(604) 2162000",
        "official_email": "ie.liceodeantioquia@medellin.edu.co",
        "educational_levels": "PREESCOLAR,PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-ANT-050010000012",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "050010000012",
                "name": "SEDE PRINCIPAL LICEO DE ANTIOQUIA",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 48 NO. 39-41",
                "status": "ACTIVA",
                "is_active": True,
            },
            {
                "dane_sede_code": "050010000020",
                "name": "SEDE SAN JUAN BOSCO",
                "is_main": False,
                "zone": "URBANA",
                "address": "CALLE 49 NO. 38-12",
                "status": "ACTIVA",
                "is_active": True,
            },
        ],
    },
    {
        "dane_code": "050880000123",
        "name": "INSTITUCION EDUCATIVA TOMAS CADAVID RESTREPO",
        "department_code": "05",
        "department_name": "ANTIOQUIA",
        "municipality_code": "05088",
        "municipality_name": "BELLO",
        "secretaria_code": "05088",
        "secretaria_name": "SECRETARIA DE EDUCACION DE BELLO",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "TÉCNICO",
        "official_address": "CALLE 50 NO. 45-20",
        "official_phone": "(604) 4821000",
        "official_email": "ietomascadavid@belloeduca.gov.co",
        "educational_levels": "PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-ANT-050880000123",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "050880000123",
                "name": "SEDE PRINCIPAL",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 50 NO. 45-20",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 3. VALLE DEL CAUCA (76)
    {
        "dane_code": "760010000055",
        "name": "INSTITUCION EDUCATIVA SANTA LIBRADA",
        "department_code": "76",
        "department_name": "VALLE DEL CAUCA",
        "municipality_code": "76001",
        "municipality_name": "CALI",
        "secretaria_code": "76001",
        "secretaria_name": "SECRETARIA DE EDUCACION DE CALI",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CARRERA 15 NO. 5-70",
        "official_phone": "(602) 8834500",
        "official_email": "rectoria@santalibradacali.edu.co",
        "educational_levels": "PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-VAL-760010000055",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "760010000055",
                "name": "SEDE CENTRAL SANTA LIBRADA",
                "is_main": True,
                "zone": "URBANA",
                "address": "CARRERA 15 NO. 5-70",
                "status": "ACTIVA",
                "is_active": True,
            },
            {
                "dane_sede_code": "760010000063",
                "name": "SEDE LA MILAGROSA",
                "is_main": False,
                "zone": "URBANA",
                "address": "CALLE 4 NO. 14-22",
                "status": "ACTIVA",
                "is_active": True,
            },
        ],
    },
    {
        "dane_code": "765200000140",
        "name": "INSTITUCION EDUCATIVA CARDENAS CENTRO",
        "department_code": "76",
        "department_name": "VALLE DEL CAUCA",
        "municipality_code": "76520",
        "municipality_name": "PALMIRA",
        "secretaria_code": "76520",
        "secretaria_name": "SECRETARIA DE EDUCACION DE PALMIRA",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CALLE 31 NO. 32-15",
        "official_phone": "(602) 2723000",
        "official_email": "cardenascentro@palmira.edu.co",
        "educational_levels": "PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-VAL-765200000140",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "765200000140",
                "name": "SEDE PRINCIPAL CARDENAS",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 31 NO. 32-15",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 4. ATLÁNTICO (08) - Leading zero preservation
    {
        "dane_code": "080010001122",
        "name": "COLEGIO DE BARRANQUILLA (CODEBA)",
        "department_code": "08",
        "department_name": "ATLANTICO",
        "municipality_code": "08001",
        "municipality_name": "BARRANQUILLA",
        "secretaria_code": "08001",
        "secretaria_name": "SECRETARIA DE EDUCACION DE BARRANQUILLA",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CALLE 51 NO. 41-80",
        "official_phone": "(605) 3791000",
        "official_email": "codeba@sedbarranquilla.gov.co",
        "educational_levels": "BASICA SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-ATL-080010001122",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "080010001122",
                "name": "SEDE PRINCIPAL CODEBA",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 51 NO. 41-80",
                "status": "ACTIVA",
                "is_active": True,
            },
            {
                "dane_sede_code": "080010001130",
                "name": "SEDE ANEXA PRIMARIA",
                "is_main": False,
                "zone": "URBANA",
                "address": "CALLE 53 NO. 41-20",
                "status": "ACTIVA",
                "is_active": True,
            },
        ],
    },
    {
        "dane_code": "087580000045",
        "name": "INSTITUCION EDUCATIVA DOLORES MARIA UCROS",
        "department_code": "08",
        "department_name": "ATLANTICO",
        "municipality_code": "08758",
        "municipality_name": "SOLEDAD",
        "secretaria_code": "08758",
        "secretaria_name": "SECRETARIA DE EDUCACION DE SOLEDAD",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CALLE 18 NO. 21-30",
        "official_phone": "(605) 3425000",
        "official_email": "iedoloresucros@soledad.gov.co",
        "educational_levels": "PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-ATL-087580000045",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "087580000045",
                "name": "SEDE CENTRAL",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 18 NO. 21-30",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 5. SANTANDER (68)
    {
        "dane_code": "680010000333",
        "name": "INSTITUTO TECNICO NACIONAL DE COMERCIO",
        "department_code": "68",
        "department_name": "SANTANDER",
        "municipality_code": "68001",
        "municipality_name": "BUCARAMANGA",
        "secretaria_code": "68001",
        "secretaria_name": "SECRETARIA DE EDUCACION DE BUCARAMANGA",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "TÉCNICO",
        "official_address": "CALLE 55 NO. 14-42",
        "official_phone": "(607) 6420101",
        "official_email": "rectoria@instenalco.edu.co",
        "educational_levels": "PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-SAN-680010000333",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "680010000333",
                "name": "SEDE A - INSTENALCO",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 55 NO. 14-42",
                "status": "ACTIVA",
                "is_active": True,
            },
            {
                "dane_sede_code": "680010000341",
                "name": "SEDE B - CONCENTRACION ESCOLAR",
                "is_main": False,
                "zone": "URBANA",
                "address": "CARRERA 16 NO. 54-10",
                "status": "ACTIVA",
                "is_active": True,
            },
        ],
    },
    {
        "dane_code": "680810000010",
        "name": "INSTITUCION EDUCATIVA BLANCA DURAN DE PADILLA",
        "department_code": "68",
        "department_name": "SANTANDER",
        "municipality_code": "68081",
        "municipality_name": "BARRANCABERMEJA",
        "secretaria_code": "68081",
        "secretaria_name": "SECRETARIA DE EDUCACION DE BARRANCABERMEJA",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CALLE 49 NO. 18-24",
        "official_phone": "(607) 6223000",
        "official_email": "ieblancaduran@barrancabermeja.gov.co",
        "educational_levels": "PREESCOLAR,PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-SAN-680810000010",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "680810000010",
                "name": "SEDE PRINCIPAL",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 49 NO. 18-24",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 6. BOLÍVAR (13)
    {
        "dane_code": "130010001999",
        "name": "INSTITUCION EDUCATIVA SOLEDAD ACOSTA DE SAMPER",
        "department_code": "13",
        "department_name": "BOLIVAR",
        "municipality_code": "13001",
        "municipality_name": "CARTAGENA DE INDIAS",
        "secretaria_code": "13001",
        "secretaria_name": "SECRETARIA DE EDUCACION DISTRITAL DE CARTAGENA",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "BARRIO BLAS DE LEZO MZ 25",
        "official_phone": "(605) 6690100",
        "official_email": "contactenos@iesas.edu.co",
        "educational_levels": "PREESCOLAR,PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-BOL-130010001999",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "130010001999",
                "name": "SEDE PRINCIPAL BLAS DE LEZO",
                "is_main": True,
                "zone": "URBANA",
                "address": "BARRIO BLAS DE LEZO MZ 25",
                "status": "ACTIVA",
                "is_active": True,
            },
            {
                "dane_sede_code": "130010002006",
                "name": "SEDE NUEVA VENECIA",
                "is_main": False,
                "zone": "URBANA",
                "address": "BARRIO EL SOCORRO PLAN 500",
                "status": "ACTIVA",
                "is_active": True,
            },
        ],
    },
    {
        "dane_code": "134300000080",
        "name": "INSTITUCION EDUCATIVA SAN JUAN BAUTISTA",
        "department_code": "13",
        "department_name": "BOLIVAR",
        "municipality_code": "13430",
        "municipality_name": "MAGANGUE",
        "secretaria_code": "13430",
        "secretaria_name": "SECRETARIA DE EDUCACION DE MAGANGUE",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CALLE 12 NO. 14-50",
        "official_phone": "(605) 6875000",
        "official_email": "sanjuanbautista@magangue.gov.co",
        "educational_levels": "PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-BOL-134300000080",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "134300000080",
                "name": "SEDE CENTRAL",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 12 NO. 14-50",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 7. CUNDINAMARCA (25)
    {
        "dane_code": "257540000015",
        "name": "INSTITUCION EDUCATIVA MUNICIPAL INTEGRADO DE SOACHA",
        "department_code": "25",
        "department_name": "CUNDINAMARCA",
        "municipality_code": "25754",
        "municipality_name": "SOACHA",
        "secretaria_code": "25754",
        "secretaria_name": "SECRETARIA DE EDUCACION DE SOACHA",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "TÉCNICO",
        "official_address": "CARRERA 7 NO. 13-45",
        "official_phone": "(601) 7305000",
        "official_email": "integradosoacha@soacha.gov.co",
        "educational_levels": "PREESCOLAR,PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-CUN-257540000015",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "257540000015",
                "name": "SEDE PRINCIPAL INTEGRADO",
                "is_main": True,
                "zone": "URBANA",
                "address": "CARRERA 7 NO. 13-45",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    {
        "dane_code": "258990000090",
        "name": "INSTITUCION EDUCATIVA MUNICIPAL SAN JUAN BAUTISTA DE LA SALLE",
        "department_code": "25",
        "department_name": "CUNDINAMARCA",
        "municipality_code": "25899",
        "municipality_name": "ZIPAQUIRA",
        "secretaria_code": "25899",
        "secretaria_name": "SECRETARIA DE EDUCACION DE ZIPAQUIRA",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CALLE 8 NO. 10-30",
        "official_phone": "(601) 8522000",
        "official_email": "lasalle@zipaquira.gov.co",
        "educational_levels": "PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-CUN-258990000090",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "258990000090",
                "name": "SEDE PRINCIPAL",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 8 NO. 10-30",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 8. BOYACÁ (15)
    {
        "dane_code": "150010000100",
        "name": "COLEGIO DE BOYACA",
        "department_code": "15",
        "department_name": "BOYACA",
        "municipality_code": "15001",
        "municipality_name": "TUNJA",
        "secretaria_code": "15001",
        "secretaria_name": "SECRETARIA DE EDUCACION DE TUNJA",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CALLE 19 NO. 10-64",
        "official_phone": "(608) 7422000",
        "official_email": "rectoria@colboy.edu.co",
        "educational_levels": "PREESCOLAR,PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-BOY-150010000100",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "150010000100",
                "name": "SEDE SANTANDER (PRINCIPAL)",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 19 NO. 10-64",
                "status": "ACTIVA",
                "is_active": True,
            },
            {
                "dane_sede_code": "150010000118",
                "name": "SEDE LONDOÑO",
                "is_main": False,
                "zone": "URBANA",
                "address": "CARRERA 11 NO. 20-40",
                "status": "ACTIVA",
                "is_active": True,
            },
        ],
    },
    {
        "dane_code": "152380000210",
        "name": "INSTITUCION EDUCATIVA TECNICA INDUSTRIAL JULIO FLOREZ",
        "department_code": "15",
        "department_name": "BOYACA",
        "municipality_code": "15238",
        "municipality_name": "DUITAMA",
        "secretaria_code": "15238",
        "secretaria_name": "SECRETARIA DE EDUCACION DE DUITAMA",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "TÉCNICO",
        "official_address": "CARRERA 18 NO. 14-25",
        "official_phone": "(608) 7604000",
        "official_email": "ietijulioflorez@duitama.gov.co",
        "educational_levels": "PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-BOY-152380000210",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "152380000210",
                "name": "SEDE CENTRAL",
                "is_main": True,
                "zone": "URBANA",
                "address": "CARRERA 18 NO. 14-25",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 9. CALDAS (17)
    {
        "dane_code": "170010000150",
        "name": "INSTITUTO UNIVERSITARIO DE CALDAS",
        "department_code": "17",
        "department_name": "CALDAS",
        "municipality_code": "17001",
        "municipality_name": "MANIZALES",
        "secretaria_code": "17001",
        "secretaria_name": "SECRETARIA DE EDUCACION DE MANIZALES",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CARRERA 23 NO. 49-30",
        "official_phone": "(606) 8852000",
        "official_email": "instituto@manizales.edu.co",
        "educational_levels": "PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-CAL-170010000150",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "170010000150",
                "name": "SEDE PRINCIPAL UNIVERSITARIO",
                "is_main": True,
                "zone": "URBANA",
                "address": "CARRERA 23 NO. 49-30",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 10. CAQUETÁ (18)
    {
        "dane_code": "180010000300",
        "name": "INSTITUCION EDUCATIVA NORMAL SUPERIOR DE FLORENCIA",
        "department_code": "18",
        "department_name": "CAQUETA",
        "municipality_code": "18001",
        "municipality_name": "FLORENCIA",
        "secretaria_code": "18001",
        "secretaria_name": "SECRETARIA DE EDUCACION DE FLORENCIA",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "NORMALISTA",
        "official_address": "AVENIDA CIRCUNVALAR CALLE 16",
        "official_phone": "(608) 4351000",
        "official_email": "normalflorencia@florencia.edu.co",
        "educational_levels": "PREESCOLAR,PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-CAQ-180010000300",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "180010000300",
                "name": "SEDE PRINCIPAL NORMAL",
                "is_main": True,
                "zone": "URBANA",
                "address": "AVENIDA CIRCUNVALAR CALLE 16",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 11. CAUCA (19)
    {
        "dane_code": "190010000450",
        "name": "INSTITUCION EDUCATIVA SAN AGUSTIN",
        "department_code": "19",
        "department_name": "CAUCA",
        "municipality_code": "19001",
        "municipality_name": "POPAYAN",
        "secretaria_code": "19001",
        "secretaria_name": "SECRETARIA DE EDUCACION DE POPAYAN",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CALLE 7 NO. 14-20",
        "official_phone": "(602) 8240000",
        "official_email": "sanagustin@popayan.edu.co",
        "educational_levels": "PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-CAU-190010000450",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "190010000450",
                "name": "SEDE CENTRAL",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 7 NO. 14-20",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 12. CESAR (20)
    {
        "dane_code": "200010000550",
        "name": "COLEGIO NACIONAL LOPERENA",
        "department_code": "20",
        "department_name": "CESAR",
        "municipality_code": "20001",
        "municipality_name": "VALLEDUPAR",
        "secretaria_code": "20001",
        "secretaria_name": "SECRETARIA DE EDUCACION DE VALLEDUPAR",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CALLE 16 NO. 11-40",
        "official_phone": "(605) 5742000",
        "official_email": None,
        "educational_levels": "PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-CES-200010000550",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "200010000550",
                "name": "SEDE PRINCIPAL LOPERENA",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 16 NO. 11-40",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 13. CÓRDOBA (23)
    {
        "dane_code": "230010000600",
        "name": "INSTITUCION EDUCATIVA NACIONAL JOSE MARIA CORDOBA",
        "department_code": "23",
        "department_name": "CORDOBA",
        "municipality_code": "23001",
        "municipality_name": "MONTERIA",
        "secretaria_code": "23001",
        "secretaria_name": "SECRETARIA DE EDUCACION DE MONTERIA",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CARRERA 6 NO. 30-20",
        "official_phone": "(604) 7823000",
        "official_email": "incolcordoba@monteria.edu.co",
        "educational_levels": "PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-COR-230010000600",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "230010000600",
                "name": "SEDE PRINCIPAL",
                "is_main": True,
                "zone": "URBANA",
                "address": "CARRERA 6 NO. 30-20",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 14. CHOCÓ (27)
    {
        "dane_code": "270010000700",
        "name": "INSTITUCION EDUCATIVA INTEGRADO CARRASQUILLA INDUSTRIAL",
        "department_code": "27",
        "department_name": "CHOCO",
        "municipality_code": "27001",
        "municipality_name": "QUIBDO",
        "secretaria_code": "27001",
        "secretaria_name": "SECRETARIA DE EDUCACION DE QUIBDO",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "TÉCNICO",
        "official_address": "CARRERA 7 NO. 28-50",
        "official_phone": "(604) 6712000",
        "official_email": "carrasquilla@quibdo.edu.co",
        "educational_levels": "PREESCOLAR,PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-CHO-270010000700",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "270010000700",
                "name": "SEDE PRINCIPAL CARRASQUILLA",
                "is_main": True,
                "zone": "URBANA",
                "address": "CARRERA 7 NO. 28-50",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 15. HUILA (41)
    {
        "dane_code": "410010000800",
        "name": "INSTITUCION EDUCATIVA SANTA LIBRADA DE NEIVA",
        "department_code": "41",
        "department_name": "HUILA",
        "municipality_code": "41001",
        "municipality_name": "NEIVA",
        "secretaria_code": "41001",
        "secretaria_name": "SECRETARIA DE EDUCACION DE NEIVA",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CALLE 12 NO. 12-40",
        "official_phone": "(608) 8714000",
        "official_email": "santalibradaneiva@neiva.edu.co",
        "educational_levels": "PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-HUI-410010000800",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "410010000800",
                "name": "SEDE PRINCIPAL",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 12 NO. 12-40",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 16. LA GUAJIRA (44)
    {
        "dane_code": "440010000900",
        "name": "INSTITUCION EDUCATIVA DIVINA PASTORA",
        "department_code": "44",
        "department_name": "LA GUAJIRA",
        "municipality_code": "44001",
        "municipality_name": "RIOHACHA",
        "secretaria_code": "44001",
        "secretaria_name": "SECRETARIA DE EDUCACION DE RIOHACHA",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CALLE 15 NO. 11-20",
        "official_phone": "(605) 7273000",
        "official_email": "divinapastora@riohacha.edu.co",
        "educational_levels": "PREESCOLAR,PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-GUA-440010000900",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "440010000900",
                "name": "SEDE CENTRAL",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 15 NO. 11-20",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 17. MAGDALENA (47)
    {
        "dane_code": "470010001000",
        "name": "INSTITUCION EDUCATIVA DISTRITAL LICEO CELEDON",
        "department_code": "47",
        "department_name": "MAGDALENA",
        "municipality_code": "47001",
        "municipality_name": "SANTA MARTA",
        "secretaria_code": "47001",
        "secretaria_name": "SECRETARIA DE EDUCACION DISTRITAL DE SANTA MARTA",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "AVENIDA DEL LIBERTADOR NO. 14-30",
        "official_phone": "(605) 4212000",
        "official_email": "celedon@santamarta.gov.co",
        "educational_levels": "SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-MAG-470010001000",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "470010001000",
                "name": "SEDE MONUMENTO NACIONAL",
                "is_main": True,
                "zone": "URBANA",
                "address": "AVENIDA DEL LIBERTADOR NO. 14-30",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 18. META (50)
    {
        "dane_code": "500010001100",
        "name": "COLEGIO NACIONALIZADO FEMENINO DE VILLAVICENCIO",
        "department_code": "50",
        "department_name": "META",
        "municipality_code": "50001",
        "municipality_name": "VILLAVICENCIO",
        "secretaria_code": "50001",
        "secretaria_name": "SECRETARIA DE EDUCACION DE VILLAVICENCIO",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CALLE 38 NO. 31-25",
        "official_phone": "(608) 6624000",
        "official_email": "femenino@villavicencio.edu.co",
        "educational_levels": "PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-MET-500010001100",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "500010001100",
                "name": "SEDE PRINCIPAL",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 38 NO. 31-25",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 19. NARIÑO (52)
    {
        "dane_code": "520010001200",
        "name": "INSTITUCION EDUCATIVA CIUDAD DE PASTO",
        "department_code": "52",
        "department_name": "NARINO",
        "municipality_code": "52001",
        "municipality_name": "PASTO",
        "secretaria_code": "52001",
        "secretaria_name": "SECRETARIA DE EDUCACION DE PASTO",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CALLE 14 NO. 24-50",
        "official_phone": "(602) 7235000",
        "official_email": "ciudadpasto@pasto.edu.co",
        "educational_levels": "PREESCOLAR,PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-NAR-520010001200",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "520010001200",
                "name": "SEDE CENTRAL CCP",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 14 NO. 24-50",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 20. NORTE DE SANTANDER (54)
    {
        "dane_code": "540010001300",
        "name": "COLEGIO PROVINCIAL SAN JOSE",
        "department_code": "54",
        "department_name": "NORTE DE SANTANDER",
        "municipality_code": "54001",
        "municipality_name": "CUCUTA",
        "secretaria_code": "54001",
        "secretaria_name": "SECRETARIA DE EDUCACION DE CUCUTA",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CALLE 11 NO. 4-20",
        "official_phone": "(607) 5716000",
        "official_email": "provincialsanjose@cucuta.edu.co",
        "educational_levels": "PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-NSA-540010001300",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "540010001300",
                "name": "SEDE PRINCIPAL",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 11 NO. 4-20",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 21. QUINDÍO (63)
    {
        "dane_code": "630010001400",
        "name": "INSTITUCION EDUCATIVA CASD HERMOGENES MAZA",
        "department_code": "63",
        "department_name": "QUINDIO",
        "municipality_code": "63001",
        "municipality_name": "ARMENIA",
        "secretaria_code": "63001",
        "secretaria_name": "SECRETARIA DE EDUCACION DE ARMENIA",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "TÉCNICO",
        "official_address": "CALLE 2 NO. 19-20",
        "official_phone": "(606) 7453000",
        "official_email": "casd@armenia.edu.co",
        "educational_levels": "SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-QUI-630010001400",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "630010001400",
                "name": "SEDE CASD",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 2 NO. 19-20",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 22. RISARALDA (66)
    {
        "dane_code": "660010001500",
        "name": "INSTITUCION EDUCATIVA DEOGRACIAS CARDONA",
        "department_code": "66",
        "department_name": "RISARALDA",
        "municipality_code": "66001",
        "municipality_name": "PEREIRA",
        "secretaria_code": "66001",
        "secretaria_name": "SECRETARIA DE EDUCACION DE PEREIRA",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CALLE 21 NO. 13-18",
        "official_phone": "(606) 3348000",
        "official_email": "deogracias@pereira.edu.co",
        "educational_levels": "PREESCOLAR,PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-RIS-660010001500",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "660010001500",
                "name": "SEDE PRINCIPAL",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 21 NO. 13-18",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 23. SUCRE (70)
    {
        "dane_code": "700010001600",
        "name": "INSTITUCION EDUCATIVA ANTONIO LENIS",
        "department_code": "70",
        "department_name": "SUCRE",
        "municipality_code": "70001",
        "municipality_name": "SINCELEJO",
        "secretaria_code": "70001",
        "secretaria_name": "SECRETARIA DE EDUCACION DE SINCELEJO",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CALLE 25 NO. 21-40",
        "official_phone": "(605) 2824000",
        "official_email": "antoniolenis@sincelejo.edu.co",
        "educational_levels": "PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-SUC-700010001600",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "700010001600",
                "name": "SEDE CENTRAL LENIS",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 25 NO. 21-40",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 24. TOLIMA (73)
    {
        "dane_code": "730010001700",
        "name": "COLEGIO DE SAN SIMON",
        "department_code": "73",
        "department_name": "TOLIMA",
        "municipality_code": "73001",
        "municipality_name": "IBAGUE",
        "secretaria_code": "73001",
        "secretaria_name": "SECRETARIA DE EDUCACION DE IBAGUE",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CARRERA 5 NO. 33-60",
        "official_phone": "(608) 2641000",
        "official_email": "rectoria@sansimon.edu.co",
        "educational_levels": "PREESCOLAR,PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-TOL-730010001700",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "730010001700",
                "name": "SEDE PRINCIPAL SAN SIMON",
                "is_main": True,
                "zone": "URBANA",
                "address": "CARRERA 5 NO. 33-60",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 25. ARAUCA (81)
    {
        "dane_code": "810010001800",
        "name": "INSTITUCION EDUCATIVA SIMON BOLIVAR DE ARAUCA",
        "department_code": "81",
        "department_name": "ARAUCA",
        "municipality_code": "81001",
        "municipality_name": "ARAUCA",
        "secretaria_code": "81001",
        "secretaria_name": "SECRETARIA DE EDUCACION DEPARTAMENTAL DE ARAUCA",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CARRERA 20 NO. 18-30",
        "official_phone": "(607) 8851000",
        "official_email": "simonbolivar@arauca.edu.co",
        "educational_levels": "PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-ARA-810010001800",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "810010001800",
                "name": "SEDE CENTRAL",
                "is_main": True,
                "zone": "URBANA",
                "address": "CARRERA 20 NO. 18-30",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 26. CASANARE (85)
    {
        "dane_code": "850010001900",
        "name": "INSTITUCION EDUCATIVA BRAULIO GONZALEZ",
        "department_code": "85",
        "department_name": "CASANARE",
        "municipality_code": "85001",
        "municipality_name": "YOPAL",
        "secretaria_code": "85001",
        "secretaria_name": "SECRETARIA DE EDUCACION DE YOPAL",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "TÉCNICO",
        "official_address": "CALLE 9 NO. 23-45",
        "official_phone": "(608) 6342000",
        "official_email": "brauliogonzalez@yopal.edu.co",
        "educational_levels": "PREESCOLAR,PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-CAS-850010001900",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "850010001900",
                "name": "SEDE PRINCIPAL CENTRO",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 9 NO. 23-45",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 27. PUTUMAYO (86)
    {
        "dane_code": "860010002000",
        "name": "INSTITUCION EDUCATIVA CIUDAD MOCOA",
        "department_code": "86",
        "department_name": "PUTUMAYO",
        "municipality_code": "86001",
        "municipality_name": "MOCOA",
        "secretaria_code": "86001",
        "secretaria_name": "SECRETARIA DE EDUCACION DEPARTAMENTAL DE PUTUMAYO",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "BARRIO EL JARDIN",
        "official_phone": "(608) 4295000",
        "official_email": "ciudadmocoa@putumayo.edu.co",
        "educational_levels": "PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-PUT-860010002000",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "860010002000",
                "name": "SEDE PRINCIPAL",
                "is_main": True,
                "zone": "URBANA",
                "address": "BARRIO EL JARDIN",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 28. SAN ANDRÉS Y PROVIDENCIA (88)
    {
        "dane_code": "880010002100",
        "name": "INSTITUCION EDUCATIVA BOLIVARIANO DE SAN ANDRES",
        "department_code": "88",
        "department_name": "ARCHIPIELAGO DE SAN ANDRES PROVIDENCIA Y SANTA CATALINA",
        "municipality_code": "88001",
        "municipality_name": "SAN ANDRES",
        "secretaria_code": "88001",
        "secretaria_name": "SECRETARIA DE EDUCACION DEPARTAMENTAL DE SAN ANDRES",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "AVENIDA 20 DE JULIO",
        "official_phone": "(608) 5123000",
        "official_email": "bolivariano@sanandres.edu.co",
        "educational_levels": "PREESCOLAR,PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-SAP-880010002100",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "880010002100",
                "name": "SEDE PRINCIPAL",
                "is_main": True,
                "zone": "URBANA",
                "address": "AVENIDA 20 DE JULIO",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 29. AMAZONAS (91)
    {
        "dane_code": "910010002200",
        "name": "INSTITUCION EDUCATIVA SAGRADO CORAZON DE JESUS",
        "department_code": "91",
        "department_name": "AMAZONAS",
        "municipality_code": "91001",
        "municipality_name": "LETICIA",
        "secretaria_code": "91001",
        "secretaria_name": "SECRETARIA DE EDUCACION DEPARTAMENTAL DEL AMAZONAS",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CALLE 8 NO. 9-40",
        "official_phone": "(608) 5926000",
        "official_email": "sagradocorazon@leticia.edu.co",
        "educational_levels": "PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-AMA-910010002200",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "910010002200",
                "name": "SEDE PRINCIPAL",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 8 NO. 9-40",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 30. GUAINÍA (94)
    {
        "dane_code": "940010002300",
        "name": "INSTITUCION EDUCATIVA CUSTODIO GARCIA ROVIRA",
        "department_code": "94",
        "department_name": "GUAINIA",
        "municipality_code": "94001",
        "municipality_name": "INIRIDA",
        "secretaria_code": "94001",
        "secretaria_name": "SECRETARIA DE EDUCACION DEPARTAMENTAL DEL GUAINIA",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CALLE 16 NO. 8-15",
        "official_phone": "(608) 5656000",
        "official_email": "garciarovira@inirida.edu.co",
        "educational_levels": "PREESCOLAR,PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-GNI-940010002300",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "940010002300",
                "name": "SEDE PRINCIPAL INIRIDA",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 16 NO. 8-15",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 31. GUAVIARE (95)
    {
        "dane_code": "950010002400",
        "name": "INSTITUCION EDUCATIVA MANUEL ELKIN PATARROYO",
        "department_code": "95",
        "department_name": "GUAVIARE",
        "municipality_code": "95001",
        "municipality_name": "SAN JOSE DEL GUAVIARE",
        "secretaria_code": "95001",
        "secretaria_name": "SECRETARIA DE EDUCACION DEPARTAMENTAL DEL GUAVIARE",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "BARRIO EL DIVINO NINO",
        "official_phone": "(608) 5840000",
        "official_email": "patarroyo@guaviare.edu.co",
        "educational_levels": "PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-GVR-950010002400",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "950010002400",
                "name": "SEDE CENTRAL",
                "is_main": True,
                "zone": "URBANA",
                "address": "BARRIO EL DIVINO NINO",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 32. VAUPÉS (97)
    {
        "dane_code": "970010002500",
        "name": "INSTITUCION EDUCATIVA NORMAL SUPERIOR INDIGENA MARIA REINA",
        "department_code": "97",
        "department_name": "VAUPES",
        "municipality_code": "97001",
        "municipality_name": "MITU",
        "secretaria_code": "97001",
        "secretaria_name": "SECRETARIA DE EDUCACION DEPARTAMENTAL DEL VAUPES",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "NORMALISTA",
        "official_address": "CALLE 12 NO. 15-20",
        "official_phone": "(608) 5642000",
        "official_email": "mariareina@mitu.edu.co",
        "educational_levels": "PREESCOLAR,PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-VAU-970010002500",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "970010002500",
                "name": "SEDE PRINCIPAL NORMAL INDIGENA",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 12 NO. 15-20",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
    # 33. VICHADA (99)
    {
        "dane_code": "990010002600",
        "name": "INSTITUCION EDUCATIVA EDUARDO CARRANZA",
        "department_code": "99",
        "department_name": "VICHADA",
        "municipality_code": "99001",
        "municipality_name": "PUERTO CARRENO",
        "secretaria_code": "99001",
        "secretaria_name": "SECRETARIA DE EDUCACION DEPARTAMENTAL DEL VICHADA",
        "sector": "OFICIAL",
        "zone": "URBANA",
        "calendar": "A",
        "academic_character": "ACADÉMICO",
        "official_address": "CALLE 18 NO. 10-15",
        "official_phone": "(608) 5654000",
        "official_email": "eduardocarranza@vichada.edu.co",
        "educational_levels": "PRIMARIA,SECUNDARIA,MEDIA",
        "status": "ACTIVO",
        "is_active": True,
        "source_system": "MINISTERIO DE EDUCACION NACIONAL (DUE) / DANE",
        "source_dataset": "datos.gov.co/c36d-tcj8",
        "source_record_id": "DUE-VIC-990010002600",
        "source_updated_at": BASE_UPDATE_DATE,
        "campuses": [
            {
                "dane_sede_code": "990010002600",
                "name": "SEDE PRINCIPAL",
                "is_main": True,
                "zone": "URBANA",
                "address": "CALLE 18 NO. 10-15",
                "status": "ACTIVA",
                "is_active": True,
            }
        ],
    },
]
